### ISSUE TITLE
Search Filter not working

### ISSUE THREAD

**Issue by uzumakinaruto123** [valor-software/ng2-select#355]
The list should be filtered based on typed text. but it is not working. I tried it on demo link too , and the result is same.

Help is appreciated. Thanks

**Comment by viper31** [comment]
Did you test it on Firefox ?

What about chrome ?

**Comment by uzumakinaruto123** [comment]
@viper31  I tested it on firefox. doesn't work, On chrome , its working. any temporary workaround ?

**Comment by forik** [comment]
This issue is addressed in PR #257 but for some reason it hasn't been merged yet.

**Comment by viper31** [comment]
thx for the PR link, tested it on my side, seems ok to me.

**Comment by warapitiya** [comment]
I think this issue still there. Using Chrome 53. Can't not search elements.
